services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=auto_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - auto_manager_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

volumes:
  auto_manager_data: