services:
  app:
    build: ./app
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "8080:8080"
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=auto_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - auto_manager_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

volumes:
  auto_manager_data:
  minio-storage: